const express = require("express");
const expressAsyncHandler = require("express-async-handler");
const dotenv = require("dotenv");
const nodemailer = require("nodemailer");

dotenv.config();

const app = express();
app.use(express.json());

let transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT,
  secure: false,
  auth: {
    user: process.env.SMTP_MAIL,
    pass: process.env.SMTP_PASSWORD,
  },
});

const sendEmail = expressAsyncHandler(async (req, res) => {
  const { email, html } = req.body;

  try {
    console.log("HTML:", html);
const info = await transporter.sendMail({
  from: process.env.SMTP_MAIL,
  to: email,
  subject: "Subject",
  html: html, // Pass the HTML generated by Unlayer


    });

    console.log("Message sent: %s", info.messageId);
    res.send("Email sent");
  } catch (error) {
    console.error(error);
    res.status(500).send("Error sending email");
  }
});

app.post("email", sendEmail);

app.listen(3000, () => {
  console.log("Server started on port 3000");
});

module.exports = { sendEmail };
